### ISSUE TITLE
一部環境でClosedReceiveChannelExceptionが送出されAPIリクエストに失敗する

### ISSUE THREAD

**Issue by SlashNephy** [SlashNephy/Tweetstorm#10]
- 事象
TweetstormがTwitter APIを実行する際に`ClosedReceiveChannelException`という例外が発生しAPIリクエストに失敗します。特に決まった場所で発生するというわけではなくAPIリクエストに伴って発生しやすくなります。  
ログとスタックトレースは次のとおりです。  
```java
[ERROR] [12:03:17.195] [Penicillin.ApiAction] APIのリクエストに失敗しました. (https://api.twitter.com/1.1/lists/members/create_all.json, 1/3)
kotlinx.coroutines.experimental.channels.ClosedReceiveChannelException: Channel was closed           
        at kotlinx.coroutines.experimental.channels.Closed.getReceiveException(AbstractChannel.kt:1067)
        at kotlinx.coroutines.experimental.channels.AbstractChannel.receiveResult(AbstractChannel.kt:574)
        at kotlinx.coroutines.experimental.channels.AbstractChannel.receive(AbstractChannel.kt:567)  
        at kotlinx.coroutines.experimental.channels.ChannelCoroutine.receive$suspendImpl(ChannelCoroutine.kt)
        at kotlinx.coroutines.experimental.channels.ChannelCoroutine.receive(ChannelCoroutine.kt)    
        at io.ktor.network.tls.TLSClientHandshake$handshakes$1.doResume(TLSClientHandshake.kt:138)   
        at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)     
        at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:149)        
        at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:13)              
        at io.ktor.network.util.IOCoroutineDispatcher$IODispatchedTask.run(IOCoroutineDispatcher.kt) 
        at io.ktor.network.util.IOCoroutineDispatcher$IOThread$run$1.doResume(IOCoroutineDispatcher.kt:73)
        at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)     
        at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:149)        
        at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:13)              
        at kotlinx.coroutines.experimental.EventLoopBase.processNextEvent(EventLoop.kt:140)          
        at kotlinx.coroutines.experimental.BlockingCoroutine.joinBlocking(Builders.kt:70)            
        at kotlinx.coroutines.experimental.BuildersKt__BuildersKt.runBlocking(Builders.kt:46)        
        at kotlinx.coroutines.experimental.BuildersKt.runBlocking(Unknown Source)                    
        at io.ktor.network.util.IOCoroutineDispatcher$IOThread.run(IOCoroutineDispatcher.kt:68)
```

- 確認環境
  - Arch Linux 4.17.10-1-ARCH / openjdk 1.8.0_172

- 推測
複数アカウントで使用する際に発生することから, Ktor (Client)が使用するIOスレッドが衝突するため？

**Comment by SlashNephy** [comment]
https://github.com/SlashNephy/Tweetstorm/commit/9ed3ae2fe26a627425e29acc7c553dd21fe0ff35 で修正
